-- CreateEnum
CREATE TYPE "TaskType" AS ENUM ('FOLLOW_UP', 'GENERAL');

-- CreateEnum
CREATE TYPE "TaskLifecycleEventType" AS ENUM ('CREATED', 'RESCHEDULED', 'COMPLETED', 'CANCELLED', 'MARKED_OVERDUE', 'REOPENED');

-- AlterEnum
ALTER TYPE "ActivityType" ADD VALUE 'DISPOSITION_CHANGED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_RESCHEDULED';

-- AlterEnum
ALTER TYPE "TaskStatus" ADD VALUE 'OVERDUE';
