import { IndustryTemplateDefinition } from "../types";

export const educationTemplate: IndustryTemplateDefinition = {
  metadata: {
    key: "education",
    name: "Higher Education & EdTech",
    description: "Student counseling, academic intake, and course admission workflows for universities, institutes, and training academies.",
    version: 1,
    category: "Education",
    active: true,
    iconName: "GraduationCap",
    highlights: [
      "Target course, academic background & intake fields",
      "Counseling scheduled and fee payment dispositions",
      "Campus seminars, education fairs & digital campaign sources",
      "Bootcamp and certification program catalog",
    ],
  },
  configuration: {
    customFields: [
      {
        entityType: "LEAD",
        key: "program_interested",
        label: "Program / Course",
        description: "Academic or professional course chosen",
        fieldType: "SELECT",
        required: false,
        sortOrder: 1,
        options: ["Full Stack Web Engineering", "Data Science & AI", "Cloud & DevOps Architecture", "Cybersecurity Specialist", "Digital Product Management"],
      },
      {
        entityType: "LEAD",
        key: "highest_qualification",
        label: "Highest Qualification",
        description: "Student prior educational background",
        fieldType: "SELECT",
        required: false,
        sortOrder: 2,
        options: ["High School / 12th Standard", "Diploma", "Bachelor's Degree", "Master's Degree", "Working Professional"],
      },
      {
        entityType: "LEAD",
        key: "target_intake",
        label: "Target Batch Intake",
        description: "Target commencement cohort",
        fieldType: "SELECT",
        required: false,
        sortOrder: 3,
        options: ["Immediate Upcoming Cohort", "Next Month", "Quarter 1", "Quarter 2", "Fall Semester"],
      },
      {
        entityType: "LEAD",
        key: "scholarship_requested",
        label: "Financial Aid / Scholarship Requested",
        description: "Whether applicant requested merit or financial assistance",
        fieldType: "BOOLEAN",
        required: false,
        sortOrder: 4,
      },
      {
        entityType: "CUSTOMER",
        key: "guardian_name",
        label: "Parent / Guardian Name",
        description: "Primary family contact or fee sponsor",
        fieldType: "TEXT",
        required: false,
        sortOrder: 1,
      },
      {
        entityType: "CUSTOMER",
        key: "guardian_phone",
        label: "Guardian Contact Number",
        description: "Contact phone for fee sponsorship and emergency",
        fieldType: "PHONE",
        required: false,
        sortOrder: 2,
      },
    ],
    dispositions: [
      {
        name: "Counseling Session Scheduled",
        code: "EDU_COUNSEL_SCHEDULED",
        description: "One-on-one academic career counseling planned",
        followUpMandatory: true,
        defaultFollowUpDays: 2,
        allowEnquiryCreation: true,
      },
      {
        name: "Demo Class Attended",
        code: "EDU_DEMO_ATTENDED",
        description: "Candidate attended preview lecture; awaiting enrollment response",
        followUpMandatory: true,
        defaultFollowUpDays: 1,
        requiresNotes: true,
      },
      {
        name: "Application Submitted",
        code: "EDU_APP_SUBMITTED",
        description: "Formal enrollment documents submitted for verification",
        followUpMandatory: true,
        defaultFollowUpDays: 3,
      },
      {
        name: "Fee Paid / Enrolled",
        code: "EDU_ENROLLED",
        description: "Tuition seat booking or full fee paid",
        allowEnquiryCreation: true,
        triggersConversion: true,
      },
      {
        name: "Financial / Fee Constraint",
        code: "EDU_FEE_ISSUE",
        description: "Applicant interested but evaluating loan or payment plan",
        followUpMandatory: true,
        defaultFollowUpDays: 5,
      },
      {
        name: "Joined Competitor Institution",
        code: "EDU_JOINED_COMPETITOR",
        description: "Candidate enrolled with an alternate academy or college",
        cancelActiveFollowUp: true,
      },
    ],
    leadSources: [
      { name: "Campus Seminar / College Outreach" },
      { name: "Education Fair" },
      { name: "Website Application" },
      { name: "Alumni Referral" },
      { name: "Instagram / Social Media Ad" },
    ],
    offerings: [
      {
        name: "Full Stack Engineering Immersion (6 Months)",
        code: "COURSE-FS-6M",
        description: "Intensive career-transition bootcamp with mentor support",
        type: "SERVICE",
        price: 0,
        category: "Bootcamps",
      },
      {
        name: "Executive AI & Machine Learning Track",
        code: "COURSE-AI-EXEC",
        description: "Weekend professional upskilling program",
        type: "SERVICE",
        price: 0,
        category: "Executive Programs",
      },
      {
        name: "Foundational Tech Certification",
        code: "CERT-TECH-BASE",
        description: "Self-paced credential and assessment module",
        type: "PRODUCT",
        price: 0,
        category: "Certifications",
      },
    ],
    historyPreviewFields: ["program_interested", "target_intake", "highest_qualification"],
  },
};
