import { IndustryTemplateDefinition } from "../types";

export const generalSalesTemplate: IndustryTemplateDefinition = {
  metadata: {
    key: "general-sales",
    name: "General Sales & Commerce",
    description: "Standard pipeline, deal tracking, and qualification fields for general B2B and B2C sales organizations.",
    version: 1,
    category: "General Sales",
    active: true,
    iconName: "Briefcase",
    highlights: [
      "Estimated deal value & close date tracking",
      "Tiered lead priority scoring",
      "Meeting and proposal follow-up workflows",
      "Standard commercial service packages",
    ],
  },
  configuration: {
    customFields: [
      {
        entityType: "LEAD",
        key: "deal_value",
        label: "Estimated Deal Value",
        description: "Expected revenue from this opportunity",
        fieldType: "NUMBER",
        required: false,
        sortOrder: 1,
      },
      {
        entityType: "LEAD",
        key: "lead_priority",
        label: "Lead Priority",
        description: "Sales qualification priority",
        fieldType: "SELECT",
        required: false,
        sortOrder: 2,
        options: ["Low", "Medium", "High", "Urgent"],
      },
      {
        entityType: "LEAD",
        key: "expected_close_date",
        label: "Expected Close Date",
        description: "Target decision date",
        fieldType: "DATE",
        required: false,
        sortOrder: 3,
      },
      {
        entityType: "CUSTOMER",
        key: "industry_segment",
        label: "Industry Segment",
        description: "Customer business vertical",
        fieldType: "SELECT",
        required: false,
        sortOrder: 1,
        options: ["Technology", "Retail", "Manufacturing", "Finance", "Services", "Other"],
      },
      {
        entityType: "CUSTOMER",
        key: "tax_id",
        label: "Tax / GST Identification",
        description: "Registered business tax identifier",
        fieldType: "TEXT",
        required: false,
        sortOrder: 2,
      },
    ],
    dispositions: [
      {
        name: "Follow-up Required",
        code: "GEN_FOLLOWUP",
        description: "Prospect requested a callback or further consultation",
        followUpMandatory: true,
        defaultFollowUpDays: 3,
        requiresNotes: true,
      },
      {
        name: "Meeting Scheduled",
        code: "GEN_MEETING",
        description: "Formal discovery or demo meeting booked",
        followUpMandatory: true,
        defaultFollowUpDays: 1,
        allowEnquiryCreation: true,
      },
      {
        name: "Proposal Sent",
        code: "GEN_PROPOSAL",
        description: "Commercial proposal or quote dispatched",
        followUpMandatory: true,
        defaultFollowUpDays: 5,
      },
      {
        name: "Not Interested",
        code: "GEN_NOT_INTERESTED",
        description: "Prospect explicitly declined engagement",
        cancelActiveFollowUp: true,
      },
    ],
    leadSources: [
      { name: "Organic Search" },
      { name: "Inbound Phone" },
      { name: "LinkedIn" },
      { name: "Customer Referral" },
    ],
    offerings: [
      {
        name: "Professional Consultation Package",
        code: "CONSULT-PRO",
        description: "Standard advisory and discovery consultation",
        type: "SERVICE",
        price: 0,
        category: "Consulting",
      },
      {
        name: "Enterprise Annual Subscription",
        code: "SUB-ENT-YR",
        description: "Annual enterprise service level access",
        type: "SERVICE",
        price: 0,
        category: "Subscriptions",
      },
    ],
    historyPreviewFields: ["deal_value", "lead_priority"],
  },
};
