import { IndustryTemplateDefinition } from "../types";

export const healthcareTemplate: IndustryTemplateDefinition = {
  metadata: {
    key: "healthcare",
    name: "Healthcare & Wellness Clinics",
    description: "Inquiry intake, specialty scheduling, and treatment tracking for clinics, diagnostic centers, and wellness providers.",
    version: 1,
    category: "Healthcare",
    active: true,
    iconName: "Activity",
    highlights: [
      "Clinical specialty, preferred doctor & consultation mode",
      "Consultation scheduled & treatment plan dispositions",
      "Hospital walk-in and medical portal lead sources",
      "Standard clinic consultation and wellness therapy offerings",
    ],
  },
  configuration: {
    customFields: [
      {
        entityType: "LEAD",
        key: "consultation_specialty",
        label: "Department / Specialty",
        description: "Medical or therapeutic discipline required",
        fieldType: "SELECT",
        required: false,
        sortOrder: 1,
        options: ["General Medicine", "Ayurveda & Holistic", "Dermatology", "Dental", "Orthopedics", "Cardiology", "Physiotherapy"],
      },
      {
        entityType: "LEAD",
        key: "preferred_doctor",
        label: "Preferred Doctor / Specialist",
        description: "Name of requested consultant doctor",
        fieldType: "TEXT",
        required: false,
        sortOrder: 2,
      },
      {
        entityType: "LEAD",
        key: "preferred_appointment_date",
        label: "Preferred Appointment Date",
        description: "Patient's preferred consultation date",
        fieldType: "DATE",
        required: false,
        sortOrder: 3,
      },
      {
        entityType: "LEAD",
        key: "consultation_mode",
        label: "Consultation Mode",
        description: "Delivery mode for consultation",
        fieldType: "SELECT",
        required: false,
        sortOrder: 4,
        options: ["In-Clinic Physical Visit", "Teleconsultation / Video", "Home Visit"],
      },
      {
        entityType: "CUSTOMER",
        key: "blood_group",
        label: "Blood Group",
        description: "Patient biological blood type",
        fieldType: "SELECT",
        required: false,
        sortOrder: 1,
        options: ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"],
      },
      {
        entityType: "CUSTOMER",
        key: "emergency_contact_phone",
        label: "Emergency Contact Phone",
        description: "Primary emergency relative contact number",
        fieldType: "PHONE",
        required: false,
        sortOrder: 2,
      },
    ],
    dispositions: [
      {
        name: "Consultation Scheduled",
        code: "HC_CONSULT_SCHEDULED",
        description: "Appointment confirmed with specialist",
        followUpMandatory: true,
        defaultFollowUpDays: 1,
        allowEnquiryCreation: true,
      },
      {
        name: "Treatment Plan Issued",
        code: "HC_TREATMENT_PLAN",
        description: "Prescription or therapy package formulated; follow-up required",
        followUpMandatory: true,
        defaultFollowUpDays: 7,
        requiresNotes: true,
      },
      {
        name: "Lab Investigations Recommended",
        code: "HC_LAB_RECOMMENDED",
        description: "Diagnostic tests advised before final treatment protocol",
        followUpMandatory: true,
        defaultFollowUpDays: 3,
      },
      {
        name: "Patient No-Show",
        code: "HC_NO_SHOW",
        description: "Patient missed appointment without prior cancellation",
        followUpMandatory: true,
        defaultFollowUpDays: 2,
      },
      {
        name: "Treatment Completed",
        code: "HC_DISCHARGED",
        description: "Patient completed wellness or treatment cycle satisfactorily",
        cancelActiveFollowUp: true,
      },
    ],
    leadSources: [
      { name: "Clinic / Hospital Walk-in" },
      { name: "Doctor Referral" },
      { name: "Medical Directory (Practo/Lybrate)" },
      { name: "Health Camp / Community Outreach" },
      { name: "Emergency Helpline" },
    ],
    offerings: [
      {
        name: "Specialist Initial Consultation",
        code: "MED-CONSULT",
        description: "Comprehensive 45-minute specialist medical assessment",
        type: "SERVICE",
        price: 0,
        category: "Consultations",
      },
      {
        name: "Full Body Preventive Health Checkup",
        code: "MED-CHECKUP-FULL",
        description: "Complete blood, metabolic, and diagnostic screening",
        type: "SERVICE",
        price: 0,
        category: "Diagnostics",
      },
      {
        name: "7-Day Wellness Rejuvenation Therapy",
        code: "WELLNESS-7D",
        description: "Full therapeutic detox and revitalization regimen",
        type: "SERVICE",
        price: 0,
        category: "Therapies",
      },
    ],
    historyPreviewFields: ["consultation_specialty", "preferred_doctor", "consultation_mode"],
  },
};
