import { IndustryTemplateDefinition } from "../types";

export const realEstateTemplate: IndustryTemplateDefinition = {
  metadata: {
    key: "real-estate",
    name: "Real Estate & Properties",
    description: "Property type matching, site visit workflows, and buyer budget qualification for real estate developers and brokers.",
    version: 1,
    category: "Real Estate",
    active: true,
    iconName: "Home",
    highlights: [
      "Property type, budget range & location fields",
      "Site visit booking & negotiation dispositions",
      "Property portal and site walk-in sources",
      "Sample apartment and villa property catalog",
    ],
  },
  configuration: {
    customFields: [
      {
        entityType: "LEAD",
        key: "property_type",
        label: "Property Type",
        description: "Type of property desired",
        fieldType: "SELECT",
        required: false,
        sortOrder: 1,
        options: ["Apartment / Flat", "Independent Villa", "Residential Plot", "Commercial Office", "Retail Shop"],
      },
      {
        entityType: "LEAD",
        key: "budget_min",
        label: "Minimum Budget",
        description: "Minimum anticipated spend",
        fieldType: "NUMBER",
        required: false,
        sortOrder: 2,
      },
      {
        entityType: "LEAD",
        key: "budget_max",
        label: "Maximum Budget",
        description: "Maximum budget ceiling",
        fieldType: "NUMBER",
        required: false,
        sortOrder: 3,
      },
      {
        entityType: "LEAD",
        key: "preferred_location",
        label: "Preferred Location",
        description: "Preferred locality, sector, or neighborhood",
        fieldType: "TEXT",
        required: false,
        sortOrder: 4,
      },
      {
        entityType: "LEAD",
        key: "possession_timeline",
        label: "Possession Timeline",
        description: "Desired possession timeline",
        fieldType: "SELECT",
        required: false,
        sortOrder: 5,
        options: ["Ready to Move", "Within 6 Months", "Under Construction (1-2 yrs)", "Investment (2+ yrs)"],
      },
      {
        entityType: "CUSTOMER",
        key: "investor_type",
        label: "Buyer Persona",
        description: "End-user occupant vs. property investor",
        fieldType: "SELECT",
        required: false,
        sortOrder: 1,
        options: ["End User / Self Occupied", "Property Investor", "NRI / Overseas Buyer"],
      },
      {
        entityType: "CUSTOMER",
        key: "current_city",
        label: "Current City of Residence",
        description: "City where buyer currently resides",
        fieldType: "TEXT",
        required: false,
        sortOrder: 2,
      },
    ],
    dispositions: [
      {
        name: "Site Visit Scheduled",
        code: "RE_SITE_VISIT",
        description: "Physical property or show flat visit planned",
        followUpMandatory: true,
        defaultFollowUpDays: 2,
        allowEnquiryCreation: true,
      },
      {
        name: "Site Visit Completed",
        code: "RE_VISIT_DONE",
        description: "Client completed property inspection; feedback pending",
        followUpMandatory: true,
        defaultFollowUpDays: 1,
        requiresNotes: true,
      },
      {
        name: "Price Negotiation",
        code: "RE_NEGOTIATION",
        description: "Reviewing payment plans, discounts, or customization options",
        followUpMandatory: true,
        defaultFollowUpDays: 3,
      },
      {
        name: "Booking Advance Paid",
        code: "RE_BOOKED",
        description: "Token amount / unit booking advance received",
        allowEnquiryCreation: true,
        triggersConversion: true,
      },
      {
        name: "Location Mismatch",
        code: "RE_LOCATION_MISMATCH",
        description: "Prospect looking in geographical area outside project scope",
        cancelActiveFollowUp: true,
      },
      {
        name: "Budget Mismatch",
        code: "RE_BUDGET_MISMATCH",
        description: "Prospect budget differs significantly from pricing",
        cancelActiveFollowUp: true,
      },
    ],
    leadSources: [
      { name: "Property Portal (MagicBricks/99acres)" },
      { name: "Site Walk-in" },
      { name: "Channel Partner / Broker" },
      { name: "Newspaper Advertisement" },
      { name: "Outdoor Hoarding / Billboard" },
    ],
    offerings: [
      {
        name: "2 BHK Luxury Apartment",
        code: "UNIT-2BHK",
        description: "1250 sq ft 2-bedroom premium residence",
        type: "PRODUCT",
        price: 0,
        category: "Residential Apartments",
      },
      {
        name: "3 BHK Premium Villa",
        code: "UNIT-3BHK-VILLA",
        description: "2400 sq ft gated villa with private lawn",
        type: "PRODUCT",
        price: 0,
        category: "Villas & Plots",
      },
      {
        name: "High Street Retail Unit",
        code: "RETAIL-G01",
        description: "650 sq ft ground floor commercial retail shop",
        type: "PRODUCT",
        price: 0,
        category: "Commercial Spaces",
      },
    ],
    historyPreviewFields: ["property_type", "budget_max", "preferred_location"],
  },
};
